abstract: replacement for C<< if ($foo eq 'bar') >>
author: Hans Dieter Pearcey <hdp@cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.57
license: perl
name: Object-Enum
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor::Fast: 0
  Class::Data::Inheritable: 0
  Sub::Exporter: 0
  Sub::Install: 0
  perl: 5.6.1
version: 0.06
